<a href="https://colab.research.google.com/github/suryansh24-coder/Machine-Learning-Journey/blob/main/Binarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split , cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [4]:
df = pd.read_csv('traind.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       714 non-null    float64
 1   Fare      891 non-null    float64
 2   SibSp     891 non-null    int64
 3   Parch     891 non-null    int64
 4   Survived  891 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 34.9 KB

In [6]:
df.dropna(inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       714 non-null    float64
 1   Fare      714 non-null    float64
 2   SibSp     714 non-null    int64
 3   Parch     714 non-null    int64
 4   Survived  714 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 33.5 KB

In [9]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [10]:
df["family"] = df['SibSp'] + df['Parch']

In [11]:
df.head()

    Age     Fare  SibSp  Parch  Survived  family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [20]:
df.dropna(subset=['SibSp','Parch'], inplace=True)

In [21]:
df.head()

    Age     Fare  SibSp  Parch  Survived  family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       714 non-null    float64
 1   Fare      714 non-null    float64
 2   SibSp     714 non-null    int64
 3   Parch     714 non-null    int64
 4   Survived  714 non-null    int64
 5   family    714 non-null    int64
dtypes: float64(2), int64(4)
memory usage: 39.0 KB

In [23]:
df.columns

Index(['Age', 'Fare', 'SibSp', 'Parch', 'Survived', 'family'], dtype='object')

In [25]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [26]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [27]:
X_train.head()

      Age     Fare  SibSp  Parch  family
328  31.0  20.5250      1      1       2
73   26.0  14.4542      1      0       1
253  30.0  16.1000      1      0       1
719  33.0   7.7750      0      0       0
666  25.0  13.0000      0      0       0

In [28]:
# Without Binarization
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.6503496503496503

In [29]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.6457159624413147)

In [30]:
from sklearn.preprocessing import Binarizer

In [32]:
trf = ColumnTransformer([
    ('bins',Binarizer(copy=False),["family"])
],remainder='passthrough')

In [34]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [37]:
pd.DataFrame(X_train_trf,columns=['family','Age','Fare','SibSp','Parch'])

     family   Age      Fare  SibSp  Parch
0       1.0  31.0   20.5250    1.0    1.0
1       1.0  26.0   14.4542    1.0    0.0
2       1.0  30.0   16.1000    1.0    0.0
3       0.0  33.0    7.7750    0.0    0.0
4       0.0  25.0   13.0000    0.0    0.0
..      ...   ...       ...    ...    ...
566     1.0  46.0   61.1750    1.0    0.0
567     0.0  25.0   13.0000    0.0    0.0
568     0.0  41.0  134.5000    0.0    0.0
569     1.0  33.0   20.5250    1.0    1.0
570     0.0  33.0    7.8958    0.0    0.0

[571 rows x 5 columns]