<a href="https://colab.research.google.com/github/suryansh24-coder/Machine-Learning-Journey/blob/main/Handling_Date%26Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [7]:
date.describe()

        product_id      city_id       orders
count  1000.000000  1000.000000  1000.000000
mean   3826.379000    16.371000    17.497000
std    2217.585914     8.554211    57.357841
min       5.000000     0.000000     1.000000
25%    1935.000000    13.000000     1.000000
50%    3810.000000    16.000000     4.000000
75%    5778.000000    25.000000    12.000000
max    7585.000000    30.000000  1004.000000

In [8]:
time.describe()

                       date                                          msg
count                  1000                                         1000
unique                  999                                          966
top     2013-11-01 23:36:00  ласковая кошечка ищет своего ночного котика
freq                      2                                            4

In [9]:
date['date'] = pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [11]:
date['date_year'] = date['date'].dt.year

In [12]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [13]:
date["date_month_no"] = date["date"].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [15]:
date["Month_name"] = date["date"].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year  date_month_no Month_name
0 2019-12-10        5628       25       3       2019             12   December
1 2018-08-15        3646       14     157       2018              8     August
2 2018-10-23        1859       25       1       2018             10    October
3 2019-08-17        7292       25       1       2019              8     August
4 2019-01-06        4344       25       3       2019              1    January

In [18]:
date["Date_day"] = date["date"].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,Month_name,Date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [19]:
date['date_dow'] = date['date'].dt.dayofweek

In [20]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,Month_name,Date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [21]:
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,Month_name,Date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [26]:
date["date_is_weekend"] = np.where(date["date_dow_name"].isin(['Sunday','Saturday']),'Yes','No')
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,Month_name,Date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,No
1,2018-08-15,2018,8,August,15,2,Wednesday,No
2,2018-10-23,2018,10,October,23,1,Tuesday,No
3,2019-08-17,2019,8,August,17,5,Saturday,Yes
4,2019-01-06,2019,1,January,6,6,Sunday,Yes

In [29]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,Month_name,Date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,No,50
1,2018-08-15,2018,8,August,15,2,Wednesday,No,33
2,2018-10-23,2018,10,October,23,1,Tuesday,No,43
3,2019-08-17,2019,8,August,17,5,Saturday,Yes,33
4,2019-01-06,2019,1,January,6,6,Sunday,Yes,1

In [30]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,Month_name,Date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,No,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,No,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,No,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,Yes,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,Yes,1,1

In [32]:
date['semester'] = np.where(date['quarter'].isin([1,2]) ,1 , 2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,Month_name,Date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,No,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,No,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,No,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,Yes,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,Yes,1,1,1

In [33]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 8, 2, 11, 3, 23, 255539)

In [34]:
today - date['date']

0     2427 days 11:03:23.255539
1     2909 days 11:03:23.255539
2     2840 days 11:03:23.255539
3     2542 days 11:03:23.255539
4     2765 days 11:03:23.255539
                 ...
995   2855 days 11:03:23.255539
996   2796 days 11:03:23.255539
997   2644 days 11:03:23.255539
998   2709 days 11:03:23.255539
999   2483 days 11:03:23.255539
Name: date, Length: 1000, dtype: timedelta64[ns]

In [36]:
np.round((today-date['date'])/np.timedelta64(1,"m"),0)

0      3495543.0
1      4189623.0
2      4090263.0
3      3661143.0
4      3982263.0
         ...
995    4111863.0
996    4026903.0
997    3808023.0
998    3901623.0
999    3576183.0
Name: date, Length: 1000, dtype: float64

In [37]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [39]:
time.drop(columns=['msg'])
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [40]:
time['hours'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time.head()

,date,msg,hours,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [41]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hours,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [43]:
today-time['date']
(today -time['date'])/np.timedelta64(1,"m")

0      6.643333e+06
1      6.447563e+06
2      7.147362e+06
3      6.142232e+06
4      6.713992e+06
           ...
995    7.563493e+06
996    6.585829e+06
997    7.255406e+06
998    7.422449e+06
999    6.374138e+06
Name: date, Length: 1000, dtype: float64