<a href="https://colab.research.google.com/github/suryansh24-coder/Machine-Learning-Journey/blob/main/MICE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression

In [3]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [9]:
df = df.iloc[:,0:-1].copy()

In [5]:
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [10]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [11]:
df.head()

    R&D Spend  Administration
21        8.0            15.0
37        NaN             5.0
2        15.0            10.0
14       12.0             NaN
44        2.0             NaN

In [15]:
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())

In [16]:
df0

    R&D Spend  Administration
21       8.00            15.0
37       9.25             5.0
2       15.00            10.0
14      12.00            10.0
44       2.00            10.0

In [17]:
df1 = df0.copy()

In [18]:
df1.iloc[1,0] = np.nan
df1

    R&D Spend  Administration
21        8.0            15.0
37        NaN             5.0
2        15.0            10.0
14       12.0            10.0
44        2.0            10.0

In [19]:
X = df1.iloc[[0,2,3,4],1:3]
X

    Administration
21            15.0
2             10.0
14            10.0
44            10.0

In [21]:
y = df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [24]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[[1],1:2])

array([11.33333333])

In [25]:
df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration
21        8.0            15.0
37        NaN             5.0
2        15.0            10.0
14       12.0             NaN
44        2.0            10.0

In [29]:
# Select rows where neither 'R&D Spend' nor 'Administration' are NaN for training
# Use 'R&D Spend' as the feature (column 0)
X = df1.iloc[[0,2,4],[0]]
X

    R&D Spend  Administration
21        8.0            15.0
37        NaN             5.0
2        15.0            10.0
44        2.0            10.0

In [27]:
# Select 'Administration' as the target (column 1) for the corresponding training rows
y = df1.iloc[[0,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    10.0
Name: Administration, dtype: float64