<a href="https://colab.research.google.com/github/suryansh24-coder/Machine-Learning-Journey/blob/main/MLPipeline03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline , make_pipeline
from sklearn.feature_selection import SelectKBest ,chi2
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv("traind.csv")

In [11]:
df.head(2)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C

In [6]:
df.drop(columns=["PassengerId","Name","Ticket","Cabin"], inplace=True)

In [7]:
x = df.drop(columns=["Survived"])
y = df["Survived"]

In [9]:
X_train ,X_test ,y_train ,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
X_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [12]:
y_train.sample(5)

636    0
56     1
704    0
241    1
766    0
Name: Survived, dtype: int64

In [13]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [16]:
# Imputation Transformer
trf1 = ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('Impute_embarked', SimpleImputer(strategy='most_frequent'),[6])
    ],remainder='passthrough')

In [18]:
# One hot Encoding
trf2 = ColumnTransformer([
    ('ohe_sex_embarked', OneHotEncoder(sparse_output=False, handle_unknown='ignore'),[1,6])
] , remainder='passthrough')

In [22]:
# Scaling
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

In [23]:
# Feature Selection
trf4 = SelectKBest(score_func=chi2 , k=5)

In [24]:
# train the model
trf5 = DecisionTreeClassifier()

In [25]:
pipe = Pipeline([
    ('trf1',trf1) ,
    ('trf2',trf2) ,
    ('trf2',trf3) ,
    ('trf4',trf4) ,
    ('trf5',trf5)
])

In [26]:
# Alternative Syntax
pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5)

In [27]:
pipe.fit(X_train , y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('Impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=5,
                             score_func=<function chi2 at 0x7f79c89298a0>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [32]:
pipe.named_steps

{'columntransformer-1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('Impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'columntransformer-2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'columntransformer-3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'selectkbest': SelectKBest(k=5, score_func=<function chi2 at 0x7f79c89298a0>),
 'decisiontreeclassifier': DecisionTreeClassifier()}

In [ ]:
pipe.named_steps['trf1'].transformers_[0][1].statistics_

In [28]:
from sklearn import set_config

In [29]:
set_config(display='diagram')

In [30]:
y_pred = pipe.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.6256983240223464

In [35]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0])

In [37]:
# Cross Validation
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train , y_train , cv=5 , scoring='accuracy').mean()

np.float64(0.6391214419383433)

In [39]:
# Grid Search using Pipeline
params= {
    'trf5__max_depth' : [1,2,3,4,5,None]
}

In [41]:
from sklearn.model_selection import GridSearchCV
# Corrected parameters dictionary to use the pipeline's internal step name
params = {
    'decisiontreeclassifier__max_depth' : [1,2,3,4,5,None]
}
grid = GridSearchCV(pipe, params , cv=5 , scoring='accuracy')
grid.fit(X_train , y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer-1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('Impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('columntransformer-2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_embarked',
                                                                         OneHotEncoder(handle_unkno...ore',
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          6])])),
                                       ('columntransformer-3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('selectkbest',
                                        SelectKBest(k=5,
                                                    score_func=<function chi2 at 0x7f79c89298a0>)),
                                       ('decisiontreeclassifier',
                                        DecisionTreeClassifier())]),
             param_grid={'decisiontreeclassifier__max_depth': [1, 2, 3, 4, 5,
                                                               None]},
             scoring='accuracy')

In [42]:
grid.best_score_

np.float64(0.6391214419383433)

In [43]:
grid.best_params_

{'decisiontreeclassifier__max_depth': 2}

In [44]:
# Export
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))