<a href="https://colab.research.google.com/github/suryansh24-coder/Machine-Learning-Journey/blob/main/Understanding_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
pd.read_csv('train.csv')

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,26,92,2011-08-26,87235.57,False,61.10,3.796,NaN,NaN,NaN,NaN,NaN,136.213613,7.767,A,152513
1,34,22,2011-03-25,5945.97,False,53.11,3.480,NaN,NaN,NaN,NaN,NaN,128.616064,10.398,A,158114
2,21,28,2010-12-03,1219.89,False,50.43,2.708,NaN,NaN,NaN,NaN,NaN,211.265543,8.163,B,140167
3,8,9,2010-09-17,11972.71,False,75.32,2.582,NaN,NaN,NaN,NaN,NaN,214.878556,6.315,A,155078
4,19,55,2012-05-18,8271.82,False,58.81,4.029,12613.98,NaN,11.50,1705.28,3600.79,138.106581,8.150,A,203819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282446,27,18,2012-10-19,20775.91,False,56.53,4.153,2639.32,NaN,4.77,575.48,3147.23,142.863363,8.000,A,204184
282447,39,36,2010-05-21,5350.00,False,76.67,2.826,NaN,NaN,NaN,NaN,NaN,209.392294,8.464,A,184109
282448,14,29,2010-04-30,10939.87,False,53.15,2.921,NaN,NaN,NaN,NaN,NaN,181.662036,8.899,A,200898
282449,15,90,2011-07-01,5013.89,False,67.43,3.916,NaN,NaN,NaN,NaN,NaN,135.446800,7.806,B,123737
282450,13,32,2011-10-14,8103.12,False,51.74,3.567,NaN,NaN,NaN,NaN,NaN,129.770645,6.392,A,219622

In [5]:
df = pd.read_csv('train.csv')
df.shape

(282451, 16)

In [6]:
df.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,26,92,2011-08-26,87235.57,False,61.10,3.796,NaN,NaN,NaN,NaN,NaN,136.213613,7.767,A,152513
1,34,22,2011-03-25,5945.97,False,53.11,3.480,NaN,NaN,NaN,NaN,NaN,128.616064,10.398,A,158114
2,21,28,2010-12-03,1219.89,False,50.43,2.708,NaN,NaN,NaN,NaN,NaN,211.265543,8.163,B,140167
3,8,9,2010-09-17,11972.71,False,75.32,2.582,NaN,NaN,NaN,NaN,NaN,214.878556,6.315,A,155078
4,19,55,2012-05-18,8271.82,False,58.81,4.029,12613.98,NaN,11.5,1705.28,3600.79,138.106581,8.150,A,203819

In [7]:
df.sample(6)

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
202227,28,1,2010-02-19,30763.19,False,54.83,2.915,NaN,NaN,NaN,NaN,NaN,126.526286,13.975,A,206302
124702,35,35,2012-08-17,2396.15,False,76.51,3.807,3038.67,NaN,NaN,1401.93,2672.55,142.215738,8.839,B,103681
225982,5,74,2011-09-02,3715.81,False,90.38,3.533,NaN,NaN,NaN,NaN,NaN,216.358850,6.529,B,34875
206413,36,79,2011-02-18,17865.26,False,57.48,3.017,NaN,NaN,NaN,NaN,NaN,212.006352,8.395,A,39910
6873,21,10,2010-07-16,15985.64,False,85.61,2.623,NaN,NaN,NaN,NaN,NaN,210.757795,8.099,B,140167
7494,5,22,2011-05-20,1934.27,False,71.37,3.907,NaN,NaN,NaN,NaN,NaN,216.302385,6.489,B,34875

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282451 entries, 0 to 282450
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         282451 non-null  int64
 1   Dept          282451 non-null  int64
 2   Date          282451 non-null  object
 3   Weekly_Sales  282451 non-null  float64
 4   IsHoliday     282451 non-null  bool
 5   Temperature   282451 non-null  float64
 6   Fuel_Price    282451 non-null  float64
 7   MarkDown1     100520 non-null  float64
 8   MarkDown2     74232 non-null   float64
 9   MarkDown3     91521 non-null   float64
 10  MarkDown4     90031 non-null   float64
 11  MarkDown5     101029 non-null  float64
 12  CPI           282451 non-null  float64
 13  Unemployment  282451 non-null  float64
 14  Type          282451 non-null  object
 15  Size          282451 non-null  int64
dtypes: bool(1), float64(10), int64(3), object(2)
memory usage: 32.6+ MB

In [12]:
df.notnull().sum()

Store           282451
Dept            282451
Date            282451
Weekly_Sales    282451
IsHoliday       282451
Temperature     282451
Fuel_Price      282451
MarkDown1       100520
MarkDown2        74232
MarkDown3        91521
MarkDown4        90031
MarkDown5       101029
CPI             282451
Unemployment    282451
Type            282451
Size            282451
dtype: int64

In [14]:
df.isnull()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,False,False,False,False,False,False,False,True,True,True,True,True,False,False,False,False
1,False,False,False,False,False,False,False,True,True,True,True,True,False,False,False,False
2,False,False,False,False,False,False,False,True,True,True,True,True,False,False,False,False
3,False,False,False,False,False,False,False,True,True,True,True,True,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282446,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
282447,False,False,False,False,False,False,False,True,True,True,True,True,False,False,False,False
282448,False,False,False,False,False,False,False,True,True,True,True,True,False,False,False,False
282449,False,False,False,False,False,False,False,True,True,True,True,True,False,False,False,False
282450,False,False,False,False,False,False,False,True,True,True,True,True,False,False,False,False

In [19]:
df["Weekly_Sales"] = df["Weekly_Sales"].fillna(df["Weekly_Sales"].mean())

In [20]:
df

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,26,92,2011-08-26,87235.57,False,61.10,3.796,NaN,NaN,NaN,NaN,NaN,136.213613,7.767,A,152513
1,34,22,2011-03-25,5945.97,False,53.11,3.480,NaN,NaN,NaN,NaN,NaN,128.616064,10.398,A,158114
2,21,28,2010-12-03,1219.89,False,50.43,2.708,NaN,NaN,NaN,NaN,NaN,211.265543,8.163,B,140167
3,8,9,2010-09-17,11972.71,False,75.32,2.582,NaN,NaN,NaN,NaN,NaN,214.878556,6.315,A,155078
4,19,55,2012-05-18,8271.82,False,58.81,4.029,12613.98,NaN,11.50,1705.28,3600.79,138.106581,8.150,A,203819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282446,27,18,2012-10-19,20775.91,False,56.53,4.153,2639.32,NaN,4.77,575.48,3147.23,142.863363,8.000,A,204184
282447,39,36,2010-05-21,5350.00,False,76.67,2.826,NaN,NaN,NaN,NaN,NaN,209.392294,8.464,A,184109
282448,14,29,2010-04-30,10939.87,False,53.15,2.921,NaN,NaN,NaN,NaN,NaN,181.662036,8.899,A,200898
282449,15,90,2011-07-01,5013.89,False,67.43,3.916,NaN,NaN,NaN,NaN,NaN,135.446800,7.806,B,123737
282450,13,32,2011-10-14,8103.12,False,51.74,3.567,NaN,NaN,NaN,NaN,NaN,129.770645,6.392,A,219622

In [22]:
df["IsHoliday"] = df["IsHoliday"].fillna(df["IsHoliday"].mean())

In [23]:
df

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,26,92,2011-08-26,87235.57,False,61.10,3.796,NaN,NaN,NaN,NaN,NaN,136.213613,7.767,A,152513
1,34,22,2011-03-25,5945.97,False,53.11,3.480,NaN,NaN,NaN,NaN,NaN,128.616064,10.398,A,158114
2,21,28,2010-12-03,1219.89,False,50.43,2.708,NaN,NaN,NaN,NaN,NaN,211.265543,8.163,B,140167
3,8,9,2010-09-17,11972.71,False,75.32,2.582,NaN,NaN,NaN,NaN,NaN,214.878556,6.315,A,155078
4,19,55,2012-05-18,8271.82,False,58.81,4.029,12613.98,NaN,11.50,1705.28,3600.79,138.106581,8.150,A,203819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282446,27,18,2012-10-19,20775.91,False,56.53,4.153,2639.32,NaN,4.77,575.48,3147.23,142.863363,8.000,A,204184
282447,39,36,2010-05-21,5350.00,False,76.67,2.826,NaN,NaN,NaN,NaN,NaN,209.392294,8.464,A,184109
282448,14,29,2010-04-30,10939.87,False,53.15,2.921,NaN,NaN,NaN,NaN,NaN,181.662036,8.899,A,200898
282449,15,90,2011-07-01,5013.89,False,67.43,3.916,NaN,NaN,NaN,NaN,NaN,135.446800,7.806,B,123737
282450,13,32,2011-10-14,8103.12,False,51.74,3.567,NaN,NaN,NaN,NaN,NaN,129.770645,6.392,A,219622

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282451 entries, 0 to 282450
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         282451 non-null  int64
 1   Dept          282451 non-null  int64
 2   Date          282451 non-null  object
 3   Weekly_Sales  282451 non-null  float64
 4   IsHoliday     282451 non-null  bool
 5   Temperature   282451 non-null  float64
 6   Fuel_Price    282451 non-null  float64
 7   MarkDown1     100520 non-null  float64
 8   MarkDown2     74232 non-null   float64
 9   MarkDown3     91521 non-null   float64
 10  MarkDown4     90031 non-null   float64
 11  MarkDown5     101029 non-null  float64
 12  CPI           282451 non-null  float64
 13  Unemployment  282451 non-null  float64
 14  Type          282451 non-null  object
 15  Size          282451 non-null  int64
dtypes: bool(1), float64(10), int64(3), object(2)
memory usage: 32.6+ MB

In [25]:
df.describe()

,Store,Dept,Weekly_Sales,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Size
count,282451.000000,282451.000000,282451.000000,282451.000000,282451.000000,100520.000000,74232.000000,91521.000000,90031.000000,101029.000000,282451.000000,282451.000000,282451.000000
mean,22.193166,44.286138,15983.429692,60.113640,3.360300,7246.077559,3318.408122,1417.397841,3379.591745,4639.476021,171.207802,7.968098,136730.073220
std,12.782138,30.503641,22661.092494,18.446485,0.458602,8254.606267,9485.575898,9547.858949,6269.428446,6060.459590,39.160808,1.868070,61002.319363
min,1.000000,1.000000,-4988.940000,-2.060000,2.472000,0.270000,-265.760000,-29.100000,0.220000,135.160000,126.064000,3.879000,34875.000000
25%,11.000000,18.000000,2079.330000,46.780000,2.932000,2241.190000,40.960000,5.060000,508.100000,1877.810000,132.022667,6.891000,93638.000000
50%,22.000000,38.000000,7616.550000,62.150000,3.452000,5363.520000,191.820000,24.340000,1482.030000,3364.410000,182.350989,7.866000,140167.000000
75%,33.000000,74.000000,20245.745000,74.290000,3.737000,9235.590000,1919.790000,103.130000,3607.570000,5563.800000,212.464799,8.572000,202505.000000
max,45.000000,99.000000,693099.360000,100.140000,4.468000,88646.760000,104519.540000,141630.610000,67474.850000,108519.280000,227.232807,14.313000,219622.000000

In [26]:
df.isnull().sum()

Store                0
Dept                 0
Date                 0
Weekly_Sales         0
IsHoliday            0
Temperature          0
Fuel_Price           0
MarkDown1       181931
MarkDown2       208219
MarkDown3       190930
MarkDown4       192420
MarkDown5       181422
CPI                  0
Unemployment         0
Type                 0
Size                 0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
 df.drop(["MarkDown1","MarkDown2","MarkDown3","MarkDown4","MarkDown5"], axis=1)

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,CPI,Unemployment,Type,Size
0,26,92,2011-08-26,87235.57,False,61.10,3.796,136.213613,7.767,A,152513
1,34,22,2011-03-25,5945.97,False,53.11,3.480,128.616064,10.398,A,158114
2,21,28,2010-12-03,1219.89,False,50.43,2.708,211.265543,8.163,B,140167
3,8,9,2010-09-17,11972.71,False,75.32,2.582,214.878556,6.315,A,155078
4,19,55,2012-05-18,8271.82,False,58.81,4.029,138.106581,8.150,A,203819
...,...,...,...,...,...,...,...,...,...,...,...
282446,27,18,2012-10-19,20775.91,False,56.53,4.153,142.863363,8.000,A,204184
282447,39,36,2010-05-21,5350.00,False,76.67,2.826,209.392294,8.464,A,184109
282448,14,29,2010-04-30,10939.87,False,53.15,2.921,181.662036,8.899,A,200898
282449,15,90,2011-07-01,5013.89,False,67.43,3.916,135.446800,7.806,B,123737
282450,13,32,2011-10-14,8103.12,False,51.74,3.567,129.770645,6.392,A,219622